kind: pipeline
type: docker
name: lint-files

platform:
  os: linux
  arch: amd64

steps:
  - name: lint_dockerfiles
    pull: if-not-exists
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile

---
kind: pipeline
type: docker
name: build and docker push

platform:
  os: linux
  arch: amd64

depends_on:
  - lint-files

trigger:
  branch:
    - master

steps:
  - name: build
    image: golang:1.13
    commands:
      - "go build -o ./myapp"

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: sever3d/golangappfromdrone # it will store images in my docker hub repo
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
    when:
      event:
        - push
      branch:
        - master

  - name: quay.io push
    image: thegeeklab/drone-docker
    privileged: true
    settings:
      registry: quay.io
      username:
        from_secret: QUAY_USERNAME
      password:
        from_secret: QUAY_PASSWORD
      repo: quay.io/sewerynmi/busybox
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}

---
kind: pipeline
type: docker
name: build notifications

trigger:
  status:
    - success
    - failure

depends_on:
  - build and docker push

slack: &slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook_url
    channel: drone-pipelines
    username: Drone

steps:
  - name: slack
    <<: *slack
    settings:
      template: |
        {{#success build.status}}
          <${DRONE_BUILD_LINK}|Build #{{ build.number }}> succeeded! :tada:
        {{else}}
          <${DRONE_BUILD_LINK}|Build #{{ build.number }}> failed :broken_heart:
        {{/success}}
        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
        Repo: {{ repo.name }}
        Branch: <${DRONE_REPO_LINK}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
    when:
      event:
        - push
