kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.13
    commands:
      - "go build -o ./myapp"

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: sever3d/golangappfromdrone
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      when:
      event:
        - push
      branch:
        - master

trigger:
  branch:
    - master
