kind: pipeline
type: kubernetes
name: lint-files

platform:
  os: linux
  arch: amd64

steps:
  - name: lit_dockerfiles
    pull: if-not-exists
    image: hadolint/hadolint
    commands:
      - hadolint Dockerfile

---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

depends_on:
  - lint-files

trigger:
  branch:
    - master

steps:
  - name: build
    image: golang:1.13
    commands:
      - "go build -o ./myapp"

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: sever3d/golangappfromdrone # it will store images in my docker hub repo
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
    when:
      event:
        - push
      branch:
        - master
