---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: expressdroneapp
          image: {{ .Values.image.repo }}expressdroneapp:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          imagePullPolicy: Always