---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3001
      protocol: TCP
