name: Docker
on:
  push:
    branches:
      - master
      - "**EAHW-**"
      - "**eahw/**"
      - "**eahw-**"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    env:
      QUAY_REGISTRY: quay.io/sewerynmi
      QUAY_REPO: expressdroneapp
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.15.0"

      - run: npm ci

      - name: Get image tags
        id: image-tags
        run: |
          echo 'IMAGE_TAG<<EOF' >> $GITHUB_ENV
          if [ "$GITHUB_REF_NAME" = "main" ]
          then
            echo 'latest' >> $GITHUB_ENV
          else
            [[ $GITHUB_REF_NAME =~ (EAHW-[0-9]*) ]] && TAG=${match/#E/E}${BASH_REMATCH/#E/E}
            echo ${TAG} >> $GITHUB_ENV
          fi
          echo 'EOF' >> $GITHUB_ENV

      - name: Build and publish image to Quay
        uses: docker/build-push-action@v1
        with:
          registry: QUAY_REGISTRY
          repository: expressdroneapp
          username: ${{ secrets.QUAY_ROBOT_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
          tags: "${{ env.IMAGE_TAG }}"

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
