name: Docker
on:
  push:
    branches:
      - master
      - "**EAHW-**"
      - "**eahw/**"
      - "**eahw-**"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    env:
      QUAY_REGISTRY: quay.io/sewerynmi
      QUAY_REPO: expressdroneapp
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.15.0"

      - run: npm ci

      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'

      - name: Get image tags
        id: image-tags
        run: |
          if [ "$GITHUB_REF_NAME" = "master" ]
          then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            [[ $GITHUB_REF_NAME =~ (EAHW-[0-9]*) ]] && TAG=${match/#E/E}${BASH_REMATCH/#E/E}
            echo "IMAGE_TAG=happy-tag" >> $GITHUB_ENV
          fi
          echo "${{ env.IMAGE_TAG }}"

      - name: Build and publish image to Quay
        uses: docker/build-push-action@v1
        with:
          registry: QUAY_REGISTRY
          repository: expressdroneapp
          username: ${{ secrets.QUAY_ROBOT_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
          tags: "${{ env.IMAGE_TAG }}"

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
