name: Docker
on:
  push:
    branches:
      - master
      - "**eahw-**"
      - "**EAHW-**"

jobs:
  build-docker-image:
    runs-on: ubuntu-20.04
    env:
      QUAY_REGISTRY: quay.io/sewerynmi
      QUAY_REPO: expressdroneapp
    steps:
      - uses: actions/checkout@v2

      - name: Get Image Tags
        id: image-tags
        shell: bash
        run: |
          if [ "$GITHUB_REF_NAME" = "master" ]; then
            echo "image_tag=latest" >> $GITHUB_ENV
          fi
          if [[ $GITHUB_REF_NAME =~ (eahw-[0-9]*|EAHW-[0-9]*) ]] && TAG=${match/#E/E}${BASH_REMATCH/#E/E}; then
            TAG_UPPERCASE=$(echo "$TAG" | tr '[:lower:]' '[:upper:]')
            echo "image_tag=${TAG_UPPERCASE}" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: expressdroneapp
          tags: ${{ env.image_tag }}
          containerfiles: |
            ./Dockerfile

      - name: Push image to Quay
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.QUAY_REGISTRY}}
          username: ${{ secrets.QUAY_ROBOT_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
